name: sitesurface_flutter_chat
description: Integrate full-blown chat to your existing application with few lines of code.
version: 0.0.4
homepage: https://sitesurface.com
repository: https://github.com/Sitesurface/sitesurface_flutter_chat

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.1.0
  firebase_messaging: ^14.1.2
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_local_notifications: ^13.0.0
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  lints: ^2.0.1
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
flutter:

false_secrets:
 - lib/src/widget/message_item.dart
 - example/
